version: '3'

# Internal Docker network - isolate projects for better containerization
networks:
  spott:
    driver: bridge

# This allows you to stop and restart the db service without losing data.
volumes:
  db:
    driver: local

services:

# Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - spott
    restart: unless-stopped

# MySQL Service
  mysql:
    container_name: mysqldb
    build: ./sql/MySQL
    tty: true  # enable cli to interact with this container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spottdb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - spott
    restart: unless-stopped

# App Service
  php:
    build: ./src
    container_name: app
    ports:
      - "9000:9000"
#    env_file: ./src/.env
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: php
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/ver-7-2/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - spott
    restart: unless-stopped